server:
  port: 80
debug: true
spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411 # 监控链地址
  sleuth:
    sampler:
      probability: 1 #采样率值介于 0 到 1 之间，1 则表示全部采集
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true #是否从EurekaServer获取已有的注册信息，默认为ture
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
