server:
  port: 3344

spring:
  application:
    name:  cloud-configcenter-server #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HouChongmu/Learning.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
          - springcloud-config
      ####读取分支
      label: springcloud-learning
# http://localhost:3344/springcloud-learning/file-name直接获取配置文件
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka