server:
  port: 8004
spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: 192.168.17.130:2181

  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    # 一定要有端口号和服务名称
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
      driver-class-name: com.mysql.jdbc.Driver #数据库驱动包
      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password: root

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.yolyn.springcloud.entities  #所有entity别名所在包

